apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-frontend
  labels:
    app: kanban-frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: kanban-frontend
  template:
    metadata:
      labels:
        app: kanban-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: ghcr.io/siddy0307-hash/kanban-frontend:0abde519
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
